# Generated by Django 5.0.1 on 2024-01-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file_url',
            field=models.FileField(upload_to='certificate_files/'),
        ),
    ]
