# Generated by Django 5.0.1 on 2024-01-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_rename_file_url_certificate_file_certificate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(),
        ),
    ]
