# Generated by Django 5.0.1 on 2024-01-26 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_certificate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certificates.certificatetype'),
        ),
    ]
